version: "2"
networks:
  internal_network:
    driver: bridge
    internal: true
    ipam:
      config:
      - subnet: 172.24.24.0/24
services:
  editor:
    build:
      context: .
      dockerfile: Dockerfile-editor
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./editor/editor.html:/app/editor.html:ro
    environment:
      DISPLAY: $DISPLAY
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 8080:8080
    networks: 
      - internal_network
    volumes:
      - ./data/conf/server.conf:/app/server.conf:ro
      - ./data/maps:/app/maps:ro
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./data/conf/client.conf:/app/client.conf:ro
      - ./data/sounds:/app/sounds:ro
      - ./data/sprites:/app/sprites:ro
    devices:
      - /dev/snd:/dev/snd
    environment:
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: ""
      ALSA_CARD: 0
    networks: 
      - internal_network
    depends_on:
      - server
  cadvisor:
    image: google/cadvisor:v0.32.0
    ports:
        - "8080:8080"
    volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker/:/var/lib/docker:ro"
        - "/dev/disk/:/dev/disk:ro"